# Generated by Django 5.2.8 on 2026-02-14 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
