# Generated by Django 5.2.8 on 2026-02-25 03:14

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=bookings.models.generate_short_booking_id, editable=False, max_length=50, unique=True),
        ),
    ]
