# Generated by Django 5.2.8 on 2026-02-14 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=100, unique=True)),
                ('machine_name', models.CharField(max_length=255)),
                ('machine_type', models.CharField(choices=[('Happy Seeder', 'Happy Seeder'), ('Super Seeder', 'Super Seeder'), ('Smart Seeder', 'Smart Seeder'), ('Mulcher', 'Mulcher'), ('Rotavator', 'Rotavator'), ('Zero Tillage Drill', 'Zero Tillage Drill'), ('Straw Baler', 'Straw Baler'), ('Straw Reaper', 'Straw Reaper'), ('Straw Chopper', 'Straw Chopper'), ('Paddy Thresher', 'Paddy Thresher'), ('Wheat Thresher', 'Wheat Thresher'), ('Chaff Cutter', 'Chaff Cutter'), ('Disc Harrow', 'Disc Harrow'), ('Cultivator', 'Cultivator'), ('Laser Land Leveller', 'Laser Land Leveller'), ('Reaper Binder', 'Reaper Binder'), ('Baler', 'Baler'), ('Rake', 'Rake'), ('Straw Collection Machine', 'Straw Collection Machine'), ('Other', 'Other')], max_length=50)),
                ('purchase_year', models.IntegerField()),
                ('funding_source', models.CharField(blank=True, help_text='Scheme Name or Funding Source', max_length=255, null=True)),
                ('status', models.CharField(choices=[('Idle', 'Idle'), ('In Use', 'In Use'), ('Maintenance', 'Maintenance'), ('Out of Service', 'Out of Service')], default='Idle', max_length=20)),
                ('total_hours_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_used_date', models.DateTimeField(blank=True, null=True)),
                ('last_serviced_date', models.DateField(blank=True, null=True)),
                ('next_service_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='chc.chc')),
            ],
        ),
    ]
