# Generated by Django 5.2.8 on 2026-02-14 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('chc', '0001_initial'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=255)),
                ('farmer_contact', models.CharField(max_length=10)),
                ('farmer_aadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('usage_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_meter_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('end_meter_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('crop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('area_covered', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('residue_managed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fuel_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='bookings.booking')),
                ('chc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='chc.chc')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='machines.machine')),
            ],
        ),
    ]
