# Generated by Django 5.2.8 on 2026-02-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineusage',
            options={'ordering': ['-usage_date', '-start_time']},
        ),
    ]
