# Generated by Django 5.2.8 on 2026-02-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chc',
            options={'ordering': ['-registration_date']},
        ),
    ]
