# Generated by Django 5.2.8 on 2026-02-22 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chc', '0002_alter_chc_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chc',
            name='admin_name',
        ),
    ]
