# Generated by Django 5.2.8 on 2026-02-14 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chc', '0001_initial'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('farmer_name', models.CharField(max_length=255)),
                ('farmer_contact', models.CharField(max_length=10)),
                ('farmer_email', models.EmailField(max_length=254)),
                ('farmer_aadhar', models.CharField(help_text='12-digit Aadhar Number', max_length=12)),
                ('field_area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='chc.chc')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='machines.machine')),
            ],
        ),
    ]
